export enum ARBOLUS_COLORS {
  bColorBaseDark = '#000A3F',
  bColorBaseOrange = '#FF5A3A',
  bColorBasePurple = '#6157FC',
  bColorBaseBlue = '#0062FF',
  bColorBaseWhite = '#FFFFFF',
  bColorBaseBlack = '#000000',
  bColorSecondaryGreyDark = '#80849F',
  bColorSecondaryGreyMid = '#CCCED9',
  bColorSecondaryGreyLight = '#F2F2F5',
  bColorAccentPurpleDark = '#4E48D6',
  bColorAccentPurpleMid = '#7168FC',
  bColorAccentPurpleLight = '#A09AFD',
  bColorAccentOrangeDark = '#CC4A3B',
  bColorSecondaryAmber = '#FFCC00',
  bColorAccentAmberDark = '#E5BA0F',
  bColorSecondaryGreen = '#4CD964',
  bColorAccentGreenDark = '#3DB05D',
  bColorGrayIcon = '#80859F',
  bColorBaseDarkOp = '#000a3f1a',
  bColorSecondaryGreyLightBackground = '#FAFAFD',
  angleDefaultBackgroundColor = '#F0F0F0',
  angleDefaultColor = '#BEBEBE'
}
